### ISSUE TITLE
Consider using vim-leader-guide

### ISSUE THREAD

**Issue by toupeira** [jimmay5469/vim-spacemacs#10]
This would be great to add discoverability, and also the `SPC h k` mapping :)

[vim-leader-guide](https://github.com/hecal3/vim-leader-guide):

![](https://cloud.githubusercontent.com/assets/11238697/14471215/bbc54a40-00ed-11e6-9eb2-8b6fb247589f.png)

**Comment by ctjhoa** [comment]
can be solve by merging this project with mine https://github.com/ctjhoa/spacevim/issues/1

**Comment by jimmay5469** [comment]
Vim-leader-guide looks pretty nice, I'll have to take a deeper look at how to configure it. I'll take a look at spacevim when I get a chance too.

**Comment by jimmay5469** [comment]
@toupeira what is the `SPC h k` mapping? I don't think I've used that one. I'd be happy to add it as a separate issue.

**Comment by lverweijen** [comment]
I have added support for vim-leader-guide in my personal fork:
https://github.com/lverweijen/vim-spacemacs

Edit: It's still GPL, so feel free to cherry-pick.

**Comment by toupeira** [comment]
@jimmay5469 the `SPC h k` mapping shows all top-level bindings, e.g. `SPC` itself and those from Evil normal mode, among all the others. Not sure how hard this is to implement vs. its usefulness.

**Comment by jimmay5469** [comment]
It's actually pretty easy to use vim-leader-guide with this plugin, finally set it up for myself. I added instructions here in the readme: https://github.com/jimmay5469/vim-spacemacs#using-vim-leader-guide-for-discoverability.

I'm probably going to add group name / command description dictionaries to this plugin in the future and leave it up to the user whether they choose to use it or not.
