### ISSUE TITLE
Option to disable some spacemacs keybindings

### ISSUE THREAD

**Issue by lverweijen** [jimmay5469/vim-spacemacs#11]
Some of the spacemacs keybindings may conflict with user keybindings, keybindings defined in someone's vimrc (and sometimes by other plugins).
In my opinion, it would be best not to overwrite user keybindings.

If that's not possible, then maybe there should be an option to disable groups of spacemacs keybindings.
So, there could be an option like:

```
spacemacs#disable_keybindings="fg"
```

That would disable all spacemacs keybindings starting with <LEADER>f or <LEADER>g.

**Comment by jimmay5469** [comment]
Finally needed this myself so got around to writing it. It's in the [v0.0.2](https://github.com/jimmay5469/vim-spacemacs/releases/tag/v0.0.2) release and the README has been updated with instructions!
